"use client";
import "./styles/layout.css";
import { Provider } from "react-redux";
import store from "@/reduxToolkit/Store";
import BodyLayout from '@/components/ui/bodyLayout/BodyLayout';

// export const metadata = {
//   title: "Next.js",
//   description: "Generated by Next.js",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Provider store={store}>
        <BodyLayout>{children}</BodyLayout>
      </Provider>
    </html>
  );
}
