"use client";
import "./styles/layout.css";
import { Provider } from "react-redux";
import store from "@/reduxToolkit/Store";
import BodyLayout from "@/components/ui/bodyLayout/BodyLayout";
import Head from "next/head";

// export const metadata = {
//   title: "Next.js",
//   description: "Generated by Next.js",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta property="og:title" content="Bsac-Assistent" />
        <meta property="og:description" content="Generated by Next.js" />
      </Head>
      <Provider store={store}>
        <BodyLayout>{children}</BodyLayout>
      </Provider>
    </html>
  );
}
